libs/.mbedignore
After:
`b5692509d tools/scripts: added general makefile`
We get a build error:
```
Compile [  9.3%]: freertos_delay.c
[Fatal Error] freertos_delay.c@40,10: FreeRTOS.h: No such file or directory [ERROR] ./libs/no-OS/drivers/platform/freeRTOS/freertos_delay.c:40:10: fatal error: FreeRTOS.h: No such file or directory
40 | #include "FreeRTOS.h"
```
Avoid building freeRTOS platform by adding it to the `.mbedigore`
=> libs: ignore freeRTOS platform

.github/workflows/build_projects.yaml, .github/workflows/daily_builds.yaml
Created build .yaml file to build all the projects
=> .github/workflows: Added initial build support based on github actions

projects/ad7134_iio/STM32/.extSettings, projects/ad7134_iio/app/ad7134_iio.c, projects/ad7134_iio/app/ad7134_user_config.c, projects/ad7134_iio/app/app_config.h
Updated the ad7134_iio project with the following changes
1. Updates to extsettings to add all files from include and util directory
2. Remove debug attribute
3. Add support to AD4134 device
=> Update ad7134 iio

.github/workflows/documentation.yaml
Add separate jobs for build doc and deploy doc.
Add git reference check for main for deploy doc job run.
Add artifacts download support for the html build
files generated.
=> workflow: Update workflow for documentation build and deploy

projects/ad579x_iio/app/ad579x_iio.c, projects/ad579x_iio/app/app_config.h
1. Correct typo in int ref macro.
2. Remove output amplifier attribute in case of -10v to 10v reference since  it's always one gain option by default.
3. Multiply scale by factor of 1000 for mV conversion.
4. Add fixes in the get_scale, offset functions
=> projects: ad579x: Add minor fixes

.github/workflows/documentation.yaml
Currently, the gh-pages commit is taking the author, sha and email from the head commit from the gh-pages.
Fixup this to take from the head commit from the main branch (considering the workflow only runs on push to main).
Please note that GITHUB_SHA takes different values depending on the run context:
* push: current branch head commit sha
* pull_request: temporary merge commit sha
But since the workflow only runs on push to main, that is not an issue.
=> .github: workflow: Fixup gh-pages commit

doc/sphinx/source/projects/ad719x_iio/ad719x_iio.rst, projects/ad719x_iio/README.txt, projects/ad719x_iio/app/ad719x_iio.c, projects/ad719x_iio/app/ad719x_iio.h, projects/ad719x_iio/app/ad719x_user_config.c, projects/ad719x_iio/app/app_config.c, projects/ad719x_iio/app/app_config.h, projects/ad719x_iio/ci_build.groovy
Add support for ad7194 in ad719x family.
Updated product and eval board links in the documentation. Updated Readme.txt.
=> projects:ad719x_iio:Add Support for AD7194

doc/sphinx/source/projects/ad405x_iio/ad405x_iio.rst
1. Mention STM32 platform in the 'supported carriers' section
=> doc:sphinx:ad405x_iio: Mention STM32 platform

doc/sphinx/source/iio_osc/data_streaming.rst, projects/ad405x_iio/app/ad405x_iio.c, projects/ad405x_iio/app/ad405x_iio.h, projects/ad405x_iio/app/ad405x_user_config.h, projects/ad405x_iio/app/app_config.h, projects/ad405x_iio/app/app_config_stm32.c, projects/ad405x_iio/app/app_config_stm32.h
1. Remove DMA double buffering
2. Use ping pong implementation where DMA always writes to SRAM buffer
3. Increase the size of SRAM IIO buffer to 128KB
=> projects:ad405x_iio:Add support for large capture

projects/ad7124_iio/app/app_config_stm32.c, projects/ad7124_iio/app/app_config_stm32.h
Added stm32_i2c.h in app_config_stm32.h includes.
Corrected chip select Macro in app_config_stm32.c
=> projects:ad7124_iio:Fixing STM Build error

projects/ad4170_iio/app/ad4170_iio.c
According to reports, "the AD4170 drivers don't do a sign extension when reading the ADC registers, as the ADC is
24 bits, but the int variable is 32-bit, it fills the 4th bit with zeroes even if bit 23 is 1."
The ADC output code is two's complement when the channel setup has the bipolar field configured in the AFE register.
Sign extend ADC data when the channel is in bipolar configuration.
=> Sign extend AD4170 data when channels are in bipolar configuration

projects/ad7091r_iio/STM32/.extSettings, projects/ad7091r_iio/app/ad7091r_iio.c
Update limit registers attribute setter functions. Get the latest alert recorded when both occur.
Do a read op to record if any alert is occured.
=> projects: ad7091r: Add minor updates

doc/sphinx/source/projects/ad2s1210_iio/ad2s1210_iio.rst, projects/ad2s1210_iio/README.txt
Update userguide link in readme file.
Update table alignment in GH doc rst file.
=> doc: ad2s1210: Update readme file and doc

projects/ad3530r_iio/app/ad3530r_iio.c, projects/ad3530r_iio/app/app_config.c, projects/ad3530r_iio/app/app_config_stm32.c, projects/ad3530r_iio/app/app_config_stm32.h
Resolve coverity scan warnings
Resolve compiler build warnings
=> projects: ad3530r: Resolve build warnings

libraries/.mbedignore, projects/ad4170_iio/app/ad4170_iio.c, projects/ad4170_iio/app/app_config.h
Remove the adc raw recalculation based on sign, as the offset calculation is being handled separately in the FW
Corrected the macro names being used for virtual com port in mbed platform
Updated the libraries/.mbedignore to temporarily exclude the drivers returning an error while building mbed files
=> projects:ad4170_iio: Fix build errors

projects/ad4170_iio/app/app_config.h, projects/ad4170_iio/app/app_config_stm32.h
Move macros specific to ODR/filter combination to the app_config.h
Correct the macro names of virtual com port parameters in mbed platform
=> projects:ad4170_iio: Fix build errors on mbed platform

projects/ad405x_iio/app/ad405x_iio.c, projects/ad405x_iio/app/app_config_stm32.c, projects/ad405x_iio/tests/func/test_ad405x_example.py
1. Update the application files acccording to the Coverity report
2. Add ad4050 as a device and double the value of data in test scripts
3. Add delay before eeprom read
=> projects:ad405x_iio: Resolve build warnings

doc/sphinx/source/projects/ad719x_iio/ad719x_iio.rst
Updated documentation with eval board link for AD7194
=> doc:ad719x_iio:Updated documentation

libraries/no-OS.lib, projects/ad355xr_iio/app/app_config_stm32.c, projects/ad355xr_iio/app/app_config_stm32.h, projects/ad4170_iio/app/app_config_stm32.c, projects/ad4170_iio/app/app_config_stm32.h, projects/ad469x_iio/app/app_config_stm32.c, projects/ad469x_iio/app/app_config_stm32.h, projects/ad5754r_iio/app/app_config_stm32.c, projects/ad5754r_iio/app/app_config_stm32.h, projects/ad579x_iio/app/app_config_stm32.c, projects/ad579x_iio/app/app_config_stm32.h, projects/ad7091r_iio/app/app_config_stm32.c, projects/ad7091r_iio/app/app_config_stm32.h, projects/ad7689_iio/app/app_config_stm32.c, projects/ad7689_iio/app/app_config_stm32.h, projects/ad777x_iio/app/app_config_stm32.c, projects/ad777x_iio/app/app_config_stm32.h
1. Update no-OS submodule to fetch the latest ad3530r driver changes and timer/pwm related changes.
2. Update relevant stm32_config files accordingly.
=> libraris: no-OS: Update no-OS submodule

libraries/.mbedignore
Update mbedignore to exclude the ftd2xx platform drivers
=> libraries: Update mbedignore

projects/ad4170_iio/app/ad4170_iio.c, projects/ad4170_iio/app/app_config.c, projects/ad4170_iio/app/app_config_stm32.c
1) Add ping pong buffer for Continuous DMA Mode
2) Update filter for all channels when changed via attribute 3) Move the delay function after UART Initialization 4) Correct the number of samples in the no_os_prepare_async function
=> projects:ad4170_iio: Updates to AD4170 IIO Application

projects/ad4170_iio/app/ad4170_iio.c, projects/ad4170_iio/app/app_config_stm32.c, projects/ad4170_iio/app/app_config_stm32.h
Ignore the first sample during data capture
Correct the parameters for tx trigger timer, as SPI wasn't operating at 500ksps data output rate during DMA capture
=> projects:ad4170_iio: Ignore first sample during data capture
