clone-repos.mk

Added missing clone-repos.mk file to the repository

projects:Fix build error

---

projects/ad559xr_console/ci_build.groovy
projects/ad5770r_console/ci_build.groovy
projects/ad590_console/ci_build.groovy
projects/ad5933_console/ci_build.groovy
projects/ad7124_console/ci_build.groovy
projects/ad7124_temperature-measure/ci_build.groovy
projects/ad717x_console/ci_build.groovy
projects/ad717x_iio/ci_build.groovy
projects/ad719x_iio/ci_build.groovy
projects/ad738x_iio/ci_build.groovy
projects/ad7606_iio/ci_build.groovy
projects/ad7689_iio/ci_build.groovy
projects/ad77681_iio/ci_build.groovy
projects/adt7420_console/ci_build.groovy
projects/evb_discovery_firmware/ci_build.groovy
projects/ltc268x_console/ci_build.groovy
projects/nanodac_console/ci_build.groovy

Removed parallel steps from ci_build.groovy files.
Corrected binary file path in test stage.
added firmware_builder name explicitly in node name.

projects:adxxxx: removed parallel steps

---

projects/ad559xr_console/ci_build.groovy
projects/ad5770r_console/ci_build.groovy
projects/ad590_console/ci_build.groovy
projects/ad5933_console/ci_build.groovy
projects/ad7124_console/ci_build.groovy
projects/ad7124_temperature-measure/ci_build.groovy
projects/ad717x_console/ci_build.groovy
projects/ad717x_iio/ci_build.groovy
projects/ad719x_iio/ci_build.groovy
projects/ad738x_iio/ci_build.groovy
projects/ad7606_iio/ci_build.groovy
projects/ad7689_iio/ci_build.groovy
projects/ad77681_iio/ci_build.groovy
projects/adt7420_console/ci_build.groovy
projects/evb_discovery_firmware/ci_build.groovy
projects/ltc268x_console/ci_build.groovy
projects/nanodac_console/ci_build.groovy

1.use git shell to build projects on windows

projects:adxxxx: use git shell in windows build

---

clone-repos.mk

1. Updated clone repo makefiles to use only linux shell command.

 update clone repo makefile

---

Jenkinsfile

Updated jenkinsfile by removing custom workspace

Jenkinsfile: Removed custom workspace

---

README.md

Splitting this out from #16 since it is independent of that series

README: lint using mdl and correct spelling/grammar

---

.github/workflows/check-versions.yaml

Splitting this out from #16 since it is independent of that series

github: check-versions: add checks for Mbed OS, no-OS, PCL versions

---

.github/workflows/build-projects.yaml
.gitignore

Splitting this out from #16 since it is independent of that series

Build projects using no-OS Makefiles using Github Action

---

.github/workflows/lint.yaml
projects/ad4696_iio/app/ad4696_support.c
projects/ad590_console/app/main.c
projects/ad5933_console/app/app_config.h
projects/ad5933_console/app/main.c
projects/ad719x_iio/app/ad719x_iio.c
projects/ad7606_iio/app/ad7606_support.c
projects/ad77681_iio/app/ad77681_iio.c
projects/adt7420_console/app/adt7xxx_support.h
projects/adt7420_console/app/app_config.h

I've created this pull request on top of my other one. It looks like there are few files that need to be formatted (see [job/16710913212#step:4:91](https://github.com/pamolloy/precision-converters-firmware/actions/runs/6158342207/job/16710913212#step:4:91))?
```
Formatted  projects/ad4696_iio/app/ad4696_support.c
Formatted  projects/ad590_console/app/main.c
Formatted  projects/ad5933_console/app/app_config.h
Formatted  projects/ad5933_console/app/main.c
Formatted  projects/ad719x_iio/app/ad719x_iio.c
Formatted  projects/ad7606_iio/app/ad7606_support.c
Formatted  projects/ad77681_iio/app/ad77681_iio.c
Formatted  projects/adt7420_console/app/adt7xxx_support.h
Formatted  projects/adt7420_console/app/app_config.h
```

github: lint source code with astyle

---

CONTRIBUTING.md

This list was based on an internal checklist, but has been modified to be more generally useful

CONTRIBUTING: initial documentation

---

README.md
doc/sphinx/index.rst
doc/sphinx/source/useful_links.rst

Add pcfw repository links to the documentation.
Update README.md file to link the new documentation in place of the wiki page documentation.

doc: Add link references.

---

doc/sphinx/source/projects/ad2s1210_iio/ad2s1210_iio.rst
doc/sphinx/source/projects/index.rst

Added documentation for ad2s1210 and updated TOC

doc:Add doc for ad2s1210

---

libraries/no-OS.lib

libraries:no-OS: Updated no-OS library

---

doc/sphinx/source/build/project_build.rst

Add active platform =2 for slecting stm32

doc: Adding compiler flag to doc

---

doc/sphinx/index.rst
doc/sphinx/source/contributing.rst
doc/sphinx/source/projects/ad579x_iio/ad579x_iio.rst

Update main page
Add eval board links to ad579x

Doc update

---

projects/evb_discovery_firmware/STM32/.extSettings

Updated extsettings to include the delay API from STM32

projects:evb_discovery_firmware: Updated extsettings

---

projects/ad4170_iio/app/app_config.h

projects:ad4170_iio:Modify mezzanine name

---

.github/CODEOWNERS
.gitignore

Add codeowners to add reviewers automatically for Pull Requests

Add CODEOWNERS to repository

---

projects/ad4130_iio/README.rst
projects/ad469x_iio/README.txt
projects/ad559xr_console/README.txt
projects/ad559xr_console/tests/readme.txt
projects/ad5770r_console/README.txt
projects/ad590_console/README.txt
projects/ad5933_console/README.txt
projects/ad7124_console/README.txt
projects/ad7124_temperature-measure/README.txt
projects/ad7134_iio/README.txt
projects/ad7134_iio/app/app_config.h
projects/ad717x_console/README.txt
projects/ad717x_iio/README.txt
projects/ad738x_iio/README.txt
projects/ad7606_iio/README.txt
projects/ad7689_iio/README.txt
projects/ad77681_iio/README.txt
projects/ad777x_iio/README.txt
projects/adt7420_console/README.txt
projects/ltc268x_console/README.txt
projects/nanodac_console/README.txt

Migrated all the reference links from wiki page to point to github IO docs
Updated the 'wiki' references across all files

projects:Updated link to documentation

---

doc/sphinx/source/projects/ad2s1210_iio/ad2s1210_iio.rst

Corrected the spacing in the table.

doc:ad2s1210_iio: Corrected the table

---

doc/sphinx/source/projects/index.rst

Update the entry for documentation in the index.rst

doc:ad4134_iio: Update the entry in index.rxt

---

libraries/precision-converters-library.lib
projects/_common/adi_version.h

Add adi versioning

---

projects/ad4170_iio/app/ad4170_iio.c
projects/ad4170_iio/app/app_config.h
projects/ad4170_iio/app/app_config_stm32.c

Update compile time checks to enable builds for TDM Mode

projects:ad4170_iio: Update compile time checks

---

projects/ad7606_iio/app/app_config_stm32.h

Fix build error with the UART handle

projects:ad7606_iio: Fix build errors

---

projects/ad7091r_iio/app/ad7091r_iio.c
projects/ad7091r_iio/app/app_config_stm32.c
projects/ad7091r_iio/app/app_config_stm32.h

Update init sequence with necessary delay to
fix reconnect issue on SDP-K1.

projects: ad7091r: Fix reconnect issue

---

projects/_common/common_macros.h

1)Added common_macros.h file to _common folder

project:Added common_macros.h file

---

projects/ad4080_iio/STM32/nucleo_h563/.extSettings
projects/ad4080_iio/STM32/sdp_k1/.extSettings
projects/ad4080_iio/app/app_config.c
projects/ad4080_iio/app/app_config.h

1)Removed the mbed platform support for ad4080

projects:ad4080:Removed the mbed platform support
